[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-abOSbel.json"
#target = "x86_64-unknown-none"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
